# Generated by Django 5.2.9 on 2026-01-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_delete_userphoto'),
        ('login', '0003_message_read_at'),
    ]

    operations = [
    ]
