# Generated by Django 4.2.26 on 2025-12-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('cuisine', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('price_for_two', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('has_table_booking', models.BooleanField(default=False)),
                ('pure_veg', models.BooleanField(default=False)),
                ('serves_alcohol', models.BooleanField(default=False)),
                ('rooftop', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='cafes/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guests', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cafe.cafe')),
            ],
        ),
    ]
